// DO NOT EDIT THIS FILE
const express = require('express');
const { json, urlencoded, static } = express;
const app = express();

app.use(json());
app.use(urlencoded({ extended: true }));
app.use(static('.')); // Serve static files (HTML)

app.post('/submit', (req, res) => {
  const { text1, text2, checkbox } = req.body;
  res.cookie('text1', text1, { path: '/' });
  res.cookie('text2', text2, { path: '/' });
  res.cookie('checkbox', checkbox, { path: '/' });
  res.sendStatus(200);
});

app.get('/', (req, res) => {
  res.sendFile(path.join('index.html')); // Adjust path as necessary
});

app.listen(3000, () => {
  console.log('Server running on http://localhost:3000');
});
