/**
 * DO NOT EDIT THIS FILE!
 *
 * Grader will use its own special and different version of this file
 * and your changes to this file are not used in the grading process.
 * All your code should go into the file "messages-as-json.js"
 */

function fetchUserData() {

    // This is the place where we would typically perform an API call to fetch live data from a server.
    // Since we have not yet covered important topics, such as server-side programming,
    // API design, and asynchronous communication, we will cheese it with static data.

    // dispatch custom event with the fetched data
    document.dispatchEvent(
        new CustomEvent('userDataReady', {
            detail: { jsonText },
            bubbles: true,
            cancelable: false
        })
    );
}

const jsonText = `
[{
    "id": 1,
    "firstName": "Providenci",
    "lastName": "Sipes",
    "address": {
      "streetAddress": "31248 Janis Square Apt. 689",
      "city": "Kuhicshire",
      "zipCode": "10138-6083",
      "country": "Lesotho"
    },
    "email": "Providenci_Sipes@yahoo.com",
    "username": "Providenci_Sipes",
    "homepage": "http://savanah.org/",
    "avatar": "https://picsum.photos/200?q=1",
    "phoneNumber": "918.822.9575 x96664"
  },
  {
    "id": 2,
    "firstName": "Alexandre",
    "lastName": "Kutch",
    "address": {
      "streetAddress": "484 Kuvalis Drive Suite 824",
      "city": "South Stephanieside",
      "zipCode": "95842-3272",
      "country": "Dominica"
    },
    "email": "Alexandre45@yahoo.com",
    "username": "Alexandre73",
    "homepage": "http://darion.name/",
    "avatar": "https://picsum.photos/200?q=2",
    "phoneNumber": "465.499.7109 x891"
  },
  {
    "id": 3,
    "firstName": "Scot",
    "lastName": "Glover",
    "address": {
      "streetAddress": "3406 Metz Run Suite 239",
      "city": "West Laverna",
      "zipCode": "64642",
      "country": "Lebanon"
    },
    "email": "Scot4@hotmail.com",
    "username": "Scot_Glover4",
    "homepage": "http://citlalli.org/",
    "avatar": "https://picsum.photos/200?q=3",
    "phoneNumber": "019.565.1459 x052"
  },
  {
    "id": 4,
    "firstName": "Isidro",
    "lastName": "Stracke",
    "address": {
      "streetAddress": "2464 Beier Spring Apt. 316",
      "city": "West Rowlandfort",
      "zipCode": "83813-4551",
      "country": "French Guiana"
    },
    "email": "Isidro32@hotmail.com",
    "username": "Isidro82",
    "homepage": "http://norberto.biz/",
    "avatar": "https://picsum.photos/200?q=4",
    "phoneNumber": "1-422-013-5921"
  },
  {
    "id": 5,
    "firstName": "Wilburn",
    "lastName": "Lindgren",
    "address": {
      "streetAddress": "157 Aron Pine Suite 431",
      "city": "East Eliezer",
      "zipCode": "47508-8613",
      "country": "Papua New Guinea"
    },
    "email": "Wilburn_Lindgren16@yahoo.com",
    "username": "Wilburn15",
    "homepage": "http://jose.info/",
    "avatar": "https://picsum.photos/200?q=5",
    "phoneNumber": "1-564-402-4094 x001"
  },
  {
    "id": 6,
    "firstName": "Nigel",
    "lastName": "Ernser",
    "address": {
      "streetAddress": "17348 Uriel Circle Apt. 292",
      "city": "New Rose",
      "zipCode": "14581",
      "country": "Anguilla"
    },
    "email": "Nigel_Ernser@hotmail.com",
    "username": "Nigel_Ernser29",
    "homepage": "http://marlene.name/",
    "avatar": "https://picsum.photos/200?q=6",
    "phoneNumber": "1-531-707-7381 x289"
  },
  {
    "id": 7,
    "firstName": "Oren",
    "lastName": "Predovic",
    "address": {
      "streetAddress": "5585 Renner Brooks Suite 069",
      "city": "Rhettbury",
      "zipCode": "87254-0887",
      "country": "United States of America"
    },
    "email": "Oren_Predovic@hotmail.com",
    "username": "Oren_Predovic19",
    "homepage": "http://adelia.org/",
    "avatar": "https://picsum.photos/200?q=7",
    "phoneNumber": "842-163-1286"
  },
  {
    "id": 8,
    "firstName": "Herbert",
    "lastName": "Considine",
    "address": {
      "streetAddress": "95188 Conor Mountains Suite 012",
      "city": "South Ellsworthport",
      "zipCode": "77529",
      "country": "Argentina"
    },
    "email": "Herbert_Considine@hotmail.com",
    "username": "Herbert.Considine",
    "homepage": "https://guadalupe.biz/",
    "avatar": "https://picsum.photos/200?q=8",
    "phoneNumber": "1-311-817-0070"
  },
  {
    "id": 9,
    "firstName": "Lawson",
    "lastName": "Champlin",
    "address": {
      "streetAddress": "866 Eleanora Dale Suite 775",
      "city": "West Kaitlynberg",
      "zipCode": "52086-4925",
      "country": "Botswana"
    },
    "email": "Lawson8@hotmail.com",
    "username": "Lawson_Champlin",
    "homepage": "http://kara.net/",
    "avatar": "https://picsum.photos/200?q=9",
    "phoneNumber": "838.308.7541 x54528"
  },
  {
    "id": 10,
    "firstName": "Bertrand",
    "lastName": "Koepp",
    "address": {
      "streetAddress": "4894 Mohr Fork Apt. 851",
      "city": "North Chelsea",
      "zipCode": "47924-8563",
      "country": "Burundi"
    },
    "email": "Bertrand.Koepp@hotmail.com",
    "username": "Bertrand64",
    "homepage": "http://edison.org/",
    "avatar": "https://picsum.photos/200?q=10",
    "phoneNumber": "1-458-784-8828"
  },
  {
    "id": 11,
    "firstName": "Brisa",
    "lastName": "Schamberger",
    "address": {
      "streetAddress": "353 Wilkinson Trail Suite 310",
      "city": "East Barbara",
      "zipCode": "06273-1497",
      "country": "Madagascar"
    },
    "email": "Brisa_Schamberger95@yahoo.com",
    "username": "Brisa52",
    "homepage": "http://shawna.info/",
    "avatar": "https://picsum.photos/200?q=11",
    "phoneNumber": "(449) 115-6725"
  },
  {
    "id": 12,
    "firstName": "Einar",
    "lastName": "Padberg",
    "address": {
      "streetAddress": "07500 Vandervort Plains Apt. 429",
      "city": "New Abigaleland",
      "zipCode": "29636",
      "country": "Cayman Islands"
    },
    "email": "Einar46@hotmail.com",
    "username": "Einar.Padberg",
    "homepage": "https://maggie.biz/",
    "avatar": "https://picsum.photos/200?q=12",
    "phoneNumber": "1-336-122-0950 x348"
  },
  {
    "id": 13,
    "firstName": "Gwen",
    "lastName": "Abernathy",
    "address": {
      "streetAddress": "35424 Braulio Inlet Suite 030",
      "city": "East Alvahshire",
      "zipCode": "79332-1318",
      "country": "Serbia"
    },
    "email": "Gwen.Abernathy78@hotmail.com",
    "username": "Gwen_Abernathy",
    "homepage": "http://gladys.info/",
    "avatar": "https://picsum.photos/200?q=13",
    "phoneNumber": "(431) 769-9433 x08717"
  },
  {
    "id": 14,
    "firstName": "Sonny",
    "lastName": "Kshlerin",
    "address": {
      "streetAddress": "82731 Bertha Centers Suite 654",
      "city": "Moriahfort",
      "zipCode": "60943-5250",
      "country": "Pakistan"
    },
    "email": "Sonny_Kshlerin32@gmail.com",
    "username": "Sonny.Kshlerin",
    "homepage": "http://jerod.info/",
    "avatar": "https://picsum.photos/200?q=14",
    "phoneNumber": "657.119.9689"
  },
  {
    "id": 15,
    "firstName": "Leora",
    "lastName": "Langworth",
    "address": {
      "streetAddress": "230 Marty Trafficway Apt. 523",
      "city": "Lake Leannafurt",
      "zipCode": "57913-2521",
      "country": "Saudi Arabia"
    },
    "email": "Leora.Langworth21@hotmail.com",
    "username": "Leora_Langworth21",
    "homepage": "https://terry.name/",
    "avatar": "https://picsum.photos/200?q=15",
    "phoneNumber": "1-345-188-0498"
  },
  {
    "id": 16,
    "firstName": "Sigmund",
    "lastName": "Hammes",
    "address": {
      "streetAddress": "045 Hudson Turnpike Suite 639",
      "city": "Collinsberg",
      "zipCode": "89190-3854",
      "country": "Niger"
    },
    "email": "Sigmund30@yahoo.com",
    "username": "Sigmund19",
    "homepage": "http://miles.com/",
    "avatar": "https://picsum.photos/200?q=16",
    "phoneNumber": "399.973.5995"
  },
  {
    "id": 17,
    "firstName": "Felipe",
    "lastName": "Davis",
    "address": {
      "streetAddress": "8891 Brad Mountain Suite 239",
      "city": "North Alvena",
      "zipCode": "56844",
      "country": "Angola"
    },
    "email": "Felipe90@hotmail.com",
    "username": "Felipe_Davis",
    "homepage": "http://anderson.org/",
    "avatar": "https://picsum.photos/200?q=17",
    "phoneNumber": "1-033-846-1948 x17005"
  },
  {
    "id": 18,
    "firstName": "Courtney",
    "lastName": "Bogan",
    "address": {
      "streetAddress": "3485 Murray Hills Suite 308",
      "city": "Port Rosarioburgh",
      "zipCode": "38642-5648",
      "country": "Cape Verde"
    },
    "email": "Courtney51@yahoo.com",
    "username": "Courtney_Bogan62",
    "homepage": "https://vena.name/",
    "avatar": "https://picsum.photos/200?q=18",
    "phoneNumber": "(702) 099-7349 x566"
  },
  {
    "id": 19,
    "firstName": "Paige",
    "lastName": "O'Reilly",
    "address": {
      "streetAddress": "84148 Jerde Key Suite 863",
      "city": "Greenchester",
      "zipCode": "08227",
      "country": "Malaysia"
    },
    "email": "Paige.OReilly@yahoo.com",
    "username": "Paige.OReilly",
    "homepage": "http://kieran.org/",
    "avatar": "https://picsum.photos/200?q=19",
    "phoneNumber": "1-062-740-9084 x5190"
  },
  {
    "id": 20,
    "firstName": "Marlen",
    "lastName": "Rutherford",
    "address": {
      "streetAddress": "79034 Swaniawski Course Suite 529",
      "city": "Port Hoyt",
      "zipCode": "60114-8579",
      "country": "Montenegro"
    },
    "email": "Marlen.Rutherford@gmail.com",
    "username": "Marlen_Rutherford48",
    "homepage": "http://albina.name/",
    "avatar": "https://picsum.photos/200?q=20",
    "phoneNumber": "1-084-174-6165"
  }
]
`;
